name: AttributeHider
main: io.github.warren1001.attributehider.Main
version: 3.2.0
depend: [ProtocolLib]
commands:
  attributehider:
    usage: /ah reload
    description: Reloads the AttributeHider configuration.
    aliases: [ah]